//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.TestForm.RouteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteServiceParameterRequestDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RouteServiceParameterRequestDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DS.TestForm.RouteService.RouteServiceParameterDTO originalRouteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DS.TestForm.RouteService.RouteServiceParameterDTO destinationRouteField;
        
        private DS.TestForm.RouteService.RouteType routeTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DS.TestForm.RouteService.RouteServiceParameterDTO originalRoute {
            get {
                return this.originalRouteField;
            }
            set {
                if ((object.ReferenceEquals(this.originalRouteField, value) != true)) {
                    this.originalRouteField = value;
                    this.RaisePropertyChanged("originalRoute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DS.TestForm.RouteService.RouteServiceParameterDTO destinationRoute {
            get {
                return this.destinationRouteField;
            }
            set {
                if ((object.ReferenceEquals(this.destinationRouteField, value) != true)) {
                    this.destinationRouteField = value;
                    this.RaisePropertyChanged("destinationRoute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public DS.TestForm.RouteService.RouteType routeType {
            get {
                return this.routeTypeField;
            }
            set {
                if ((this.routeTypeField.Equals(value) != true)) {
                    this.routeTypeField = value;
                    this.RaisePropertyChanged("routeType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteServiceParameterDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RouteServiceParameterDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAvenueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        private double xField;
        
        private double yField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DS.TestForm.RouteService.RouteServiceResultDTO RouteServiceResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StreetAvenueName {
            get {
                return this.StreetAvenueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAvenueNameField, value) != true)) {
                    this.StreetAvenueNameField = value;
                    this.RaisePropertyChanged("StreetAvenueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public DS.TestForm.RouteService.RouteServiceResultDTO RouteServiceResult {
            get {
                return this.RouteServiceResultField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteServiceResultField, value) != true)) {
                    this.RouteServiceResultField = value;
                    this.RaisePropertyChanged("RouteServiceResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteType", Namespace="http://tempuri.org/")]
    public enum RouteType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FastestRoute = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RouteAvoidingTraffic = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteServiceResultDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RouteServiceResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalTimeField;
        
        private double TotalDistanceField;
        
        private double TotalFuelCostField;
        
        private double TotalTollFeeCostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TotalTime {
            get {
                return this.TotalTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalTimeField, value) != true)) {
                    this.TotalTimeField = value;
                    this.RaisePropertyChanged("TotalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double TotalDistance {
            get {
                return this.TotalDistanceField;
            }
            set {
                if ((this.TotalDistanceField.Equals(value) != true)) {
                    this.TotalDistanceField = value;
                    this.RaisePropertyChanged("TotalDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double TotalFuelCost {
            get {
                return this.TotalFuelCostField;
            }
            set {
                if ((this.TotalFuelCostField.Equals(value) != true)) {
                    this.TotalFuelCostField = value;
                    this.RaisePropertyChanged("TotalFuelCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double TotalTollFeeCost {
            get {
                return this.TotalTollFeeCostField;
            }
            set {
                if ((this.TotalTollFeeCostField.Equals(value) != true)) {
                    this.TotalTollFeeCostField = value;
                    this.RaisePropertyChanged("TotalTollFeeCost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/DS.DistributedServices.RouteServices")]
    [System.SerializableAttribute()]
    public partial class TransactionExecutionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RouteService.IRouteService")]
    public interface IRouteService {
        
        // CODEGEN: Generating message contract since element name routeParameterRequest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteService/GetRoute", ReplyAction="http://tempuri.org/IRouteService/GetRouteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DS.TestForm.RouteService.TransactionExecutionFault), Action="http://tempuri.org/IRouteService/GetRouteTransactionExecutionFaultFault", Name="TransactionExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/DS.DistributedServices.RouteServices")]
        DS.TestForm.RouteService.GetRouteResponse GetRoute(DS.TestForm.RouteService.GetRouteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteService/GetRoute", ReplyAction="http://tempuri.org/IRouteService/GetRouteResponse")]
        System.Threading.Tasks.Task<DS.TestForm.RouteService.GetRouteResponse> GetRouteAsync(DS.TestForm.RouteService.GetRouteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoute", Namespace="http://tempuri.org/", Order=0)]
        public DS.TestForm.RouteService.GetRouteRequestBody Body;
        
        public GetRouteRequest() {
        }
        
        public GetRouteRequest(DS.TestForm.RouteService.GetRouteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DS.TestForm.RouteService.RouteServiceParameterRequestDTO routeParameterRequest;
        
        public GetRouteRequestBody() {
        }
        
        public GetRouteRequestBody(DS.TestForm.RouteService.RouteServiceParameterRequestDTO routeParameterRequest) {
            this.routeParameterRequest = routeParameterRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteResponse", Namespace="http://tempuri.org/", Order=0)]
        public DS.TestForm.RouteService.GetRouteResponseBody Body;
        
        public GetRouteResponse() {
        }
        
        public GetRouteResponse(DS.TestForm.RouteService.GetRouteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DS.TestForm.RouteService.RouteServiceResultDTO GetRouteResult;
        
        public GetRouteResponseBody() {
        }
        
        public GetRouteResponseBody(DS.TestForm.RouteService.RouteServiceResultDTO GetRouteResult) {
            this.GetRouteResult = GetRouteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRouteServiceChannel : DS.TestForm.RouteService.IRouteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteServiceClient : System.ServiceModel.ClientBase<DS.TestForm.RouteService.IRouteService>, DS.TestForm.RouteService.IRouteService {
        
        public RouteServiceClient() {
        }
        
        public RouteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DS.TestForm.RouteService.GetRouteResponse DS.TestForm.RouteService.IRouteService.GetRoute(DS.TestForm.RouteService.GetRouteRequest request) {
            return base.Channel.GetRoute(request);
        }
        
        public DS.TestForm.RouteService.RouteServiceResultDTO GetRoute(DS.TestForm.RouteService.RouteServiceParameterRequestDTO routeParameterRequest) {
            DS.TestForm.RouteService.GetRouteRequest inValue = new DS.TestForm.RouteService.GetRouteRequest();
            inValue.Body = new DS.TestForm.RouteService.GetRouteRequestBody();
            inValue.Body.routeParameterRequest = routeParameterRequest;
            DS.TestForm.RouteService.GetRouteResponse retVal = ((DS.TestForm.RouteService.IRouteService)(this)).GetRoute(inValue);
            return retVal.Body.GetRouteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DS.TestForm.RouteService.GetRouteResponse> DS.TestForm.RouteService.IRouteService.GetRouteAsync(DS.TestForm.RouteService.GetRouteRequest request) {
            return base.Channel.GetRouteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DS.TestForm.RouteService.GetRouteResponse> GetRouteAsync(DS.TestForm.RouteService.RouteServiceParameterRequestDTO routeParameterRequest) {
            DS.TestForm.RouteService.GetRouteRequest inValue = new DS.TestForm.RouteService.GetRouteRequest();
            inValue.Body = new DS.TestForm.RouteService.GetRouteRequestBody();
            inValue.Body.routeParameterRequest = routeParameterRequest;
            return ((DS.TestForm.RouteService.IRouteService)(this)).GetRouteAsync(inValue);
        }
    }
}
